# Generated by Django 6.0.1 on 2026-03-22 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staff_user_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to='core.staff'),
        ),
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_students', to='core.staff', verbose_name='Assigned Teacher/Advisor'),
        ),
    ]
